# Generated by Django 4.2.7 on 2023-11-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_htmx_infinite_scroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookpage',
            options={'ordering': ['number']},
        ),
    ]
